### ISSUE TITLE
Tests re-implemented in testthat fail during R CMD check

### ISSUE THREAD

**Issue by mbsabath** [IQSS/Amelia#12]
I'm working on implementing a `testthat` testing regime for Amelia, and I'm running into an issue with the `moPrep` test. The test passes when I run it in the standard R console, but fails when I run the `R CMD check`. Is there anything unique in the `mo` methods that could potentially cause this behavior?

**Comment by mattblackwell** [comment]
It looks like there was a bit of a problem with how `amelia` handled output from `moPrep` that didn't bite unless it was being called through `eval` as `testthat` does. I just pushed 42a0eb2c61b80e2998499eb4935df64e7d645870 that should solve the problem.
